### ISSUE TITLE
Does not compile with current NDK

### ISSUE THREAD

**Issue by RalfJung** [oNaiPs/droidVncServer#106]
I installed the current NDK, ran "ndk-build"; and the output ends in

```
[armeabi] Compile arm    : jpeg <= jidctint.c
[armeabi] Compile arm    : jpeg <= jidctfst.S
jni/jpeg/jidctfst.S: Assembler messages:
jni/jpeg/jidctfst.S:66: Error: missing ')'
jni/jpeg/jidctfst.S:66: Error: garbage following instruction -- `pld (r2,#0)'
jni/jpeg/jidctfst.S:259: Error: missing ')'
jni/jpeg/jidctfst.S:259: Error: garbage following instruction -- `pld (sp,#32)'
jni/jpeg/jidctfst.S:271: Error: missing ')'
jni/jpeg/jidctfst.S:271: Error: garbage following instruction -- `pld (ip,#32)'
make: *** [obj/local/armeabi/objs/jpeg/jidctfst.o] Error 1
```

**Comment by radj** [comment]
@RalfJung See #91, #80, #53.

**Comment by RalfJung** [comment]
I fixed this by disabling every architecture except for armeabi-v7. Closing as a duplicate then.

Seems like the entire project is pretty unmaintained :-/ . I ended up not having all the things it even needed for building, but the binary from the Play Store doesn't work, either.

**Comment by radj** [comment]
It is pretty inactive right now, true. Maybe you can give the forks a try?

**Comment by RalfJung** [comment]
There are 234 forks on GitHub... you don't happen to know one which is developed? ;-)

**Comment by radj** [comment]
How I wish! I will be using this project again in the future so I'll probably be doing that research then.
