### ISSUE TITLE
Trying to start the server via adb shell

### ISSUE THREAD

**Issue by 06chaynes** [oNaiPs/droidVncServer#14]
Ok so I know how to start the app from a adb shell using: 

am start -a android.intent.action.MAIN -n org.onaips.vnc/org.onaips.vnc.MainActivity

but I need help coming up with the argument to actually start the server inside the adb shell. Any help with this would be greatly appreciated!

**Comment by raininja** [comment]
The apk from the Play Store does not seem to have the androidvncserver binary included. . . I suppose I must attempt to rebuild
