### ISSUE TITLE
I got the blank screen 

### ISSUE THREAD

**Issue by carlo67** [oNaiPs/droidVncServer#21]
hey
I have the droid-VNC-server and I am using the UltraVNC 1.0.9.6.1
when I connect with UltraVNC , I got the blank screen

**Comment by mrghosh** [comment]
I have faced the same issue recently and the project seems to be abandoned (app last updated on June 11, 2012).

I tried different options under Settings->Display Access Method. The default option is auto-detect. I changed it to Framebuffer. Restarted the server and I could see the display on my viewer software. You should try all options till it works.

Tested on my ancient phone GT-S5360 running Android 2.3.5 (Better options available for recent android versions but they don't work on 2.3.5. So, I needed to find a solution by any means)
