### ISSUE TITLE
Admob

### ISSUE THREAD

**Issue by alterechtschreibung** [oNaiPs/droidVncServer#48]
We want to include droid-VNC-server in the FOSS-Market  F-Droid. Unfortunately you use Admob, which  is non free, thus it can't be included. Please remove Admob, or give us instructions how to build without Admob. 

Please get in touch with us. 

http://f-droid.org/forums/topic/droid-vnc-server/

**Comment by a-raccoon** [comment]
:(

**Comment by alexanderadam** [comment]
@dalb8 are there any news regarding AOSP support on F-Droid or is the issue still present?
