### ISSUE TITLE
VNC server won't start

### ISSUE THREAD

**Issue by ghost** [oNaiPs/droidVncServer#9]
Tried to start server but wouldn't work. It just says: "Error, can't start server".

Specs: 
Phone: HTC Desire GSM
ROM: DeFroST 6.0
Kernel:  6.0c HAVS+BFS 875mV 1113Mhz @ 998Mhz
Radio: 32.49.00.32U_5.11.05.27
Amon-RA 2.0.0 Recovery + ROM Manager Premium[/b]
Root method: UnrEVOked 3.1
HBOOT: 0.93 AlphaRev S-OFF 1.5
BlueFroST Galaxy S Theme

**Comment by capriciousduck** [comment]
I too get the same error on my old Kitkat tablet. I used the latest app. How to fix this?
