### ISSUE TITLE
Cannot to use in x86 CPU's Android - Black Screen

### ISSUE THREAD

**Issue by suujonH** [oNaiPs/droidVncServer#95]
I download  this source and successful building.It's also can perfect to run in ARM's Android pad.
But i can't run in Inter‘s x86 CPU. 

I can run the VNC Server program and use VNC Client to connect.It's a black screen,but i can click the VNC Client and control my pad.

My pad:
AOSP:   Android 4.2
CPU:     Intel Atom Z2580

thanks

**Comment by flyflypeng** [comment]
Are you modify the **APP_ABI** option in the   **jni/Applicatiion.mk** file? You need to compile the droidvncserver with `APP_ABI := x86`
